### ISSUE TITLE
Cast/ channel time on Action bar even set to ''off''

### ISSUE THREAD

**Issue by mTwsnake** [DakJaniels/FancyActionBarPlus#35]
![image](https://github.com/user-attachments/assets/50dd7b21-5c2d-487d-b04e-4d0fc09c13da)
same as arc's beam too. i already set to off and reloadui multiple times

**Comment by ACastanza** [comment]
Did you disable the Show Cast/Channel Times menu option or just set the action slot to "disable" tracking?
Also, do you have the option to enable ZOS fallback timers turned on?

**Comment by mTwsnake** [comment]
i disable the Show Cast/channel times tooltip only 
i dont see any option to enable ZOS fallback timers

**Comment by mTwsnake** [comment]
![image](https://github.com/user-attachments/assets/af648323-2e74-4af2-912f-ec0339146b29)
i think this might be the issue

**Comment by mTwsnake** [comment]
![image](https://github.com/user-attachments/assets/d099b513-b453-4521-9d84-aeda6a23fe60)
after set Delay timer fade to off, the "0" no longer display in Channel skills

**Comment by ACastanza** [comment]
Nah, there was a logic bug in the interaction between ZOS fallback timers and the Channel time setting, I just pushed a change that should fix it. You can replace the main.lua in your addons folder with the one from here and it should fix it temporarily until I get it over on ESOUI

**Comment by mTwsnake** [comment]
> Nah, there was a logic bug in the interaction between ZOS fallback timers and the Channel time setting, I just pushed a change that should fix it. You can replace the main.lua in your addons folder with the one from here and it should fix it temporarily until I get it over on ESOUI
![image](https://github.com/user-attachments/assets/2c84eb1b-5d0f-428c-96d0-72ee2e08a31a)

i have overwrite it with the one from here but this skill from fighter's guild still persist 0 while cast it

**Comment by ACastanza** [comment]
Just pushed another change that should fix this

**Comment by mTwsnake** [comment]
yes it is fixed! nice work!
